repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    - id: isort
      args: [--profile=black]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.7
    hooks:
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix, --unsafe-fixes]
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: end-of-file-fixer
    - id: check-added-large-files
      args: ['--maxkb=5024'] #5MB
    - id: check-merge-conflict
    - id: check-ast
    - id: debug-statements
    - id: check-json
    - id: check-yaml
      args: ["--unsafe"]
    - id: check-toml

-   repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.4
    hooks:
    - id: sqlfluff-lint
      args: ["--dialect=ANSI"]
    - id: sqlfluff-fix
      args: ["--dialect=ANSI"]
